version: "3"
services:
  database:
    image: "postgres:10.5"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    ports:
      - "5438:5432"
    volumes:
      - ./import.sql:/docker-entrypoint-initdb.d/init.sql
