server:
  port: 9999
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hello-world
          uri: "http://localhost:8080"
          predicates:
            - Path=/api/**
            - Method=GET
