CREATE TABLE IF NOT EXISTS FRUIT (
  IDT_FRUIT UUID NOT NULL PRIMARY KEY,
  NAM_FRUIT VARCHAR(255),
  NAM_COLOR VARCHAR(255),
  NAM_SEASON VARCHAR(255),
  IDT_REFERRER VARCHAR(36),
  IND_REFERRER VARCHAR(36),
  DAT_CREATED TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('UTC', NOW()),
  DAT_UPDATED TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('UTC', NOW())
);
