CREATE SCHEMA IF NOT EXISTS ebean_orm;

CREATE TABLE IF NOT EXISTS ebean_orm.fruit (
    IDT_FRUIT UUID NOT NULL PRIMARY KEY,
    NAM_NAME VARCHAR(255),
    TXT_COLOR VARCHAR(255),
    TXT_SEASON VARCHAR(255)
);
