CREATE TABLE IF NOT EXISTS fruit (
  IDT_FRUIT UUID NOT NULL PRIMARY KEY,
  NAM_NAME VARCHAR(255),
  TXT_COLOR VARCHAR(255),
  TXT_SEASON VARCHAR(255),
  IDT_REFERRER VARCHAR(36),
  IND_REFERRER VARCHAR(36)
);
