quarkus.http.port=8787
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

jira.base-url=${JIRA_BASE_URL:https://your-domain.atlassian.net}
jira.email=${JIRA_EMAIL:}
jira.api-token=${JIRA_API_TOKEN:}
