CREATE TABLE CUSTOMER_BALANCE
(
  IDT_CUSTOMER_BALANCE UUID           NOT NULL PRIMARY KEY,
  COD_CUSTOMER         UUID           NOT NULL UNIQUE,
  NUM_BALANCE          NUMERIC(20, 2) NOT NULL,
  DAT_CREATED          TIMESTMAP      NOT NULL
);
