version: '3'

services:
  postgresql1:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
    volumes:
      - postgresql_data:/bitnami/postgresql
    ports:
      - "5432:5432"

  postgresql2:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=user_is
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
    volumes:
      - postgresql_data:/bitnami/postgresql
    ports:
      - "5432:5432"
volumes:
  postgresql_data:
    driver: local
