CREATE TABLE BSK_SKIN_SALE_HISTORY_NO_PT (
	IDT_BSK_SKIN_SALE_HISTORY BIGSERIAL NOT NULL,
	DAT_OCCURRENCE TIMESTAMP NOT NULL,
	IND_TYPE INTEGER NOT NULL,
	NUM_PRICE DECIMAL(23, 4),
	COD_SKIN VARCHAR(255)
);

CREATE INDEX BSK_SKIN_SALE_HISTORY_NO_PT_IDX_1 ON BSK_SKIN_SALE_HISTORY_NO_PT(DAT_OCCURRENCE, IND_TYPE);
CREATE INDEX BSK_SKIN_SALE_HISTORY_NO_PT_IDX_2 ON BSK_SKIN_SALE_HISTORY_NO_PT(IDT_BSK_SKIN_SALE_HISTORY);
