quarkus.http.port=8084

# kafka

kafka.bootstrap.servers=localhost:9092
kafka.consumer.group.id=quarkus_app

## Quarkus KAFKA ##
#quarkus.messaging.blocking.signatures.execution.mode=worker
%test.mp.messaging.connector.smallrye-kafka.enabled=false
mp.messaging.connector.smallrye-kafka.bootstrap.servers=${kafka.bootstrap.servers}
mp.messaging.connector.smallrye-kafka.partitions=1
mp.messaging.connector.smallrye-kafka.session.timeout.ms=60000
mp.messaging.connector.smallrye-kafka.max.poll.interval.ms=3600000
mp.messaging.connector.smallrye-kafka.enable.auto.commit=false
mp.messaging.connector.smallrye-kafka.throttled.unprocessed-record-max-age.ms=0
mp.messaging.connector.smallrye-kafka.auto.offset.reset=earliest
mp.messaging.connector.smallrye-kafka.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.connector.smallrye-kafka.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

mp.messaging.connector.smallrye-kafka.failure-strategy=dead-letter-queue
mp.messaging.connector.smallrye-kafka.dead-letter-queue.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.connector.smallrye-kafka.dead-letter-queue.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer

### IWC - KAFKA TOPICS ##
mp.messaging.incoming."sys.ping-pong.batch".connector=smallrye-kafka
mp.messaging.incoming."sys.ping-pong.batch".batch=true
mp.messaging.incoming."sys.ping-pong.batch".group.id=sys.ping-pong.batch

# para aumentar a chance do consumidor receber lotes com mensagens de mesma key
mp.messaging.incoming."sys.ping-pong.batch".fetch.min.bytes=8192
mp.messaging.incoming."sys.ping-pong.batch".poll-timeout=10000
# na pratica nao mudou muita coisa, melhor deixar ligado que é o default pra ser mais otimizado
mp.messaging.incoming."sys.ping-pong.batch".pause-if-no-requests=true


# database jdbc
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5632/db?currentSchema=quarkus_full_example
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=3

quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=quarkus_full_example
quarkus.flyway.locations=db/migration

# logs
quarkus.log.level=INFO
quarkus.log.category."io.agroal".level=TRACE

# openapi
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui


## testing

quarkus.http.test-port=8088

%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5631/postgres?currentSchema=quarkus_full_example
%test.quarkus.datasource.username=postgres
%test.quarkus.datasource.password=postgres

thymeleaf.cache.enabled=true
%dev.thymeleaf.cache.enabled=false
