version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.0.3-ubuntu
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_DOMAIN=grafana.docker
    volumes:
      - /data/databases/stg/grafana:/var/lib/grafana
#      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  otel-collector:
    image: otel/opentelemetry-collector:0.82.0
    hostname: otel-prometheus-collector.docker
    volumes:
      - ./otelcol/config.yaml:/etc/otelcol/config.yaml
