version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.0.3-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - /data/databases/stg/grafana:/var/lib/grafana

  otel-collector:
    image: otel/opentelemetry-collector:0.82.0
    hostname: otel-prometheus-collector.docker
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
