CREATE TABLE OUTBOX_RECORD (
    IDT_OUTBOX_RECORD UUID NOT NULL,
    NAM_TOPIC VARCHAR(255),
    TXT_KEY TEXT,
    TXT_VALUE BYTEA,
    TXT_HEADERS TEXT,
    DAT_CREATED TIMESTAMP NOT NULL DEFAULT TIMEZONE('UTC', NOW()),
    CONSTRAINT OUTBOX_RECORD_PKEY PRIMARY KEY (IDT_OUTBOX_RECORD, DAT_CREATED)
) PARTITION BY RANGE (DAT_CREATED);

CREATE TABLE IF NOT EXISTS OUTBOX_RECORD_DEFAULT PARTITION OF OUTBOX_RECORD DEFAULT;
