CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS TTO_RECORD (
    IDT_TTO_RECORD UUID NOT NULL PRIMARY KEY,
    NAM_TOPIC       VARCHAR(255),
    NUM_PARTITION   NUMERIC(3, 0),
    TXT_KEY         TEXT,
    TXT_VALUE       BYTEA,
    TXT_HEADERS     TEXT,
    DAT_CREATED     TIMESTAMP NOT NULL DEFAULT TIMEZONE('UTC', NOW())
);
