CREATE TABLE IF NOT EXISTS OUTBOX_RECORD (
   IDT_OUTBOX_RECORD UUID NOT NULL PRIMARY KEY,
   NAM_TOPIC VARCHAR(255),
   TXT_KEY TEXT,
   TXT_VALUE BYTEA,
   TXT_HEADERS TEXT,
   DAT_CREATED TIMESTAMP NOT NULL DEFAULT TIMEZONE('UTC', NOW())
);
