CREATE TABLE BSK_SKIN_SALE_HISTORY (
	IDT_BSK_SKIN_SALE_HISTORY BIGSERIAL NOT NULL,
	DAT_OCCURRENCE TIMESTAMP NOT NULL,
	IND_TYPE INTEGER NOT NULL,
	NUM_PRICE DECIMAL(23, 4),
	COD_SKIN VARCHAR(255)
) PARTITION BY RANGE(DAT_OCCURRENCE, IND_TYPE);

CREATE INDEX BSK_SKIN_SALE_HISTORY_IDX_1 ON BSK_SKIN_SALE_HISTORY(DAT_OCCURRENCE, IND_TYPE);
CREATE INDEX BSK_SKIN_SALE_HISTORY_IDX2 ON BSK_SKIN_SALE_HISTORY(IDT_BSK_SKIN_SALE_HISTORY);

CREATE OR REPLACE FUNCTION createSkinSalePartition (dateFrom TEXT, dateTo TEXT, type INTEGER)
RETURNS TEXT AS $func$
DECLARE
	partitionName text;
BEGIN
	partitionName := 'BSK_SKIN_SALE_HISTORY_' || type || '_' || REPLACE(dateFrom, '-', '_');
	EXECUTE (
		'CREATE TABLE ' || partitionName || ' PARTITION OF BSK_SKIN_SALE_HISTORY
			FOR VALUES FROM ('''|| dateFrom || ''', ' || type || ') TO (''' || dateTo || ''', ' || type || ');'
	);
	RETURN 'partition created: ' || partitionName;
END;
$func$ LANGUAGE plpgsql;
