CREATE TABLE ACCOUNT (
  COD_ACCOUNT VARCHAR(20) PRIMARY KEY,
  NUM_BALANCE DECIMAL(20, 2) NOT NULL
);


CREATE TABLE STATEMENT (
    IDT_STATEMENT BIGINT PRIMARY KEY AUTO_INCREMENT,
    COD_ACCOUNT VARCHAR(20) NOT NULL,
    NUM_AMOUNT DECIMAL(20, 2) NOT NULL,
    DES_STATEMENT VARCHAR(255) NOT NULL
);
