quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=false
quarkus.flyway.migrate-at-start=true
quarkus.flyway.create-schemas=true
quarkus.flyway.default-schema=inv
quarkus.flyway.locations=db/migration
quarkus.flyway.schemas=inv
quarkus.flyway.validate-migration-naming=true
quarkus.hibernate-orm.packages=com.mageddo
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.smallrye-openapi.info-title=workflow-temporal
quarkus.smallrye-openapi.info-version=1.0.0-SNAPSHOT

%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5443/db?currentSchema=inv
%dev.quarkus.datasource.username=root
%dev.quarkus.datasource.password=root
%dev.quarkus.swagger-ui.always-include=true

sample-wallet.temporal.enabled=true
sample-wallet.temporal.namespace=default
sample-wallet.temporal.target=127.0.0.1:7233
sample-wallet.temporal.task-queue=sample-wallet-task-queue
sample-wallet.temporal.workflow-timeout=PT2M
sample-wallet.temporal.background.investment-creation-delay=PT0.05S
sample-wallet.temporal.background.candidate-processing-delay=PT0.05S
sample-wallet.temporal.background.max-candidate-attempts=2

%test.sample-wallet.temporal.enabled=false
