quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=false
quarkus.hibernate-orm.packages=com.mageddo.temporal.samplewallet.domain
quarkus.hibernate-orm.schema-management.strategy=none
