logging.level.org.ff4j=TRACE

spring.datasource.url=jdbc:h2:mem:ff4j;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

ff4j.console.enabled=true
ff4j.console.path=/actuator/features

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
