# Quarkus datasource (used by Flyway)
quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=root
%dev.quarkus.datasource.password=root
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/db?currentSchema=ebean_orm
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.jdbc.database=db

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=ebean_orm
quarkus.flyway.default-schema=ebean_orm
quarkus.flyway.create-schemas=true

# OpenAPI + Swagger UI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.http.port=8686
