# Quarkus datasource (used by Flyway)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/db?currentSchema=ebean_orm
quarkus.datasource.jdbc.driver=org.postgresql.Driver

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=ebean_orm
quarkus.flyway.default-schema=ebean_orm
quarkus.flyway.create-schemas=true

# Ebean datasource (manual bootstrapping)
datasource.db.username=root
datasource.db.password=root
datasource.db.databaseUrl=jdbc:postgresql://localhost:5434/db?currentSchema=ebean_orm
datasource.db.databaseDriver=org.postgresql.Driver
ebean.dbSchema=ebean_orm
ebean.db.ddl.generate=false
ebean.db.ddl.run=false

# OpenAPI + Swagger UI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.http.port=8080
