# Quarkus datasource (used by Flyway)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.jdbc.database=db

%dev.quarkus.datasource.username=root
%dev.quarkus.datasource.password=root
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/db?currentSchema=orm

%test.quarkus.datasource.username=postgres
%test.quarkus.datasource.password=postgres
%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5430/postgres?currentSchema=postgres


# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=orm
quarkus.flyway.default-schema=orm
quarkus.flyway.create-schemas=true

# Doma
quarkus.doma.naming=none

# OpenAPI + Swagger UI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.http.port=8686
