CREATE TABLE IF NOT EXISTS BASKET (
  IDT_BASKET UUID NOT NULL PRIMARY KEY,
  NAM_BASKET VARCHAR(255),
  DAT_CREATED TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('UTC', NOW()),
  DAT_UPDATED TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('UTC', NOW())
);
