CREATE TABLE IF NOT EXISTS TGZ_FEATURE (
	NAM_FEATURE VARCHAR(255) PRIMARY KEY NOT NULL,
	FLG_ACTIVE INTEGER,
	COD_STRATEGY VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TGZ_FEATURE_PARAMETER (
	NAM_FEATURE VARCHAR(255) NOT NULL,
	NAM_PARAMETER VARCHAR(255) NOT NULL,
	VAL_PARAMETER VARCHAR(1000),
	PRIMARY KEY(NAM_FEATURE, NAM_PARAMETER)
);
