plugins {
  id 'java'
  id 'io.quarkus' version '3.37.4'
  id 'io.ebean' version '19.3.0'
}

group = 'com.mageddo'
version = '1.0.0-SNAPSHOT'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(25)
  }
}

repositories {
  mavenCentral()
}

defaultTasks 'quarkusDev'

ext {
  ebeanVersion = '19.3.0'
  domaVersion = '3.14.0'
  quarkusDomaVersion = '1.0.9'
}

dependencies {
  implementation enforcedPlatform("io.quarkus:quarkus-bom:3.37.4")
  implementation "io.quarkus:quarkus-rest"
  implementation "io.quarkus:quarkus-rest-jackson"
  implementation "io.quarkus:quarkus-smallrye-openapi"
  implementation "io.quarkus:quarkus-swagger-ui"
  implementation "io.quarkus:quarkus-narayana-jta"
  implementation "io.quarkus:quarkus-flyway"
  implementation "io.quarkus:quarkus-jdbc-postgresql"
  testImplementation "io.quarkus:quarkus-junit5"

  implementation "io.ebean:ebean:$ebeanVersion"
  implementation "io.ebean:ebean-postgres:$ebeanVersion"
  implementation "org.seasar.doma:doma-core:$domaVersion"
  implementation "io.quarkiverse.doma:quarkus-doma:$quarkusDomaVersion"
  annotationProcessor "org.seasar.doma:doma-processor:$domaVersion"

  implementation("org.apache.commons:commons-lang3:3.20.0")

  compileOnly "org.projectlombok:lombok:1.18.46"
  annotationProcessor "org.projectlombok:lombok:1.18.46"

  testCompileOnly "org.projectlombok:lombok:1.18.46"
  testAnnotationProcessor "org.projectlombok:lombok:1.18.46"
  testImplementation "org.junit.jupiter:junit-jupiter:5.13.4"
  testImplementation "org.assertj:assertj-core:3.27.3"
  testImplementation "io.zonky.test:embedded-postgres:2.1.0"
}

ebean {
  debugLevel = 0
}

compileJava {
  options.encoding = 'UTF-8'
  options.compilerArgs += [
    '-Adoma.domain.converters=com.mageddo.fruit.config.doma.DomaDomainConverters'
  ]
}

test {
  useJUnitPlatform()
}
