{
 "title": "Coffee Maker Board",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Vezes que o JOB rodou (cumulativo)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "otel_timesRan", "legendFormat": "Vezes que rodou" }
   ]
  },
  {
   "title": "Vezes que o JOB rodou (delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "delta(sum(otel_timesRan)[1m:])", "legendFormat": "Vezes que rodou" }
   ]
  },
  {
   "title": "Quantos registros > 50ms (delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "delta(sum(otel_timeToOrderCoffee_count - ignoring(le) otel_timeToOrderCoffee_bucket{le=\"50.0\"})[1m:])",
     "legendFormat": "registros (delta)"
    }
   ]
  },
  {
   "title": "Levou mais que 50ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(otel_timeToOrderCoffee_count - ignoring(le) otel_timeToOrderCoffee_bucket{le=\"50.0\"}) / otel_timeToOrderCoffee_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}