version: '3'
services:
  build-linux-aarch64:
    image: defreitas/dns-proxy-server-build:${VERSION:-snapshot}-aarch64
    build:
      context: .
      dockerfile: Dockerfile.builder.linux-aarch64
    platform: linux/arm64/v8
