FROM ghcr.io/graalvm/graalvm-ce:22.3.1@sha256:74154179185b623f8a707449a123022299dfd97fce584eb53fcf5b145116818e
RUN gu install native-image
COPY ./ /app
WORKDIR /app

ENV JAVA_TOOL_OPTIONS='-Djdk.lang.Process.launchMechanism=fork'
RUN uname -m && ./gradlew build -Dquarkus.package.type=native \
    -Dquarkus.native.additional-build-args="-Djdk.lang.Process.launchMechanism=fork","-J-Djdk.lang.Process.launchMechanism=fork"
