logging.level.org.togglz.core=TRACE

spring.datasource.url=jdbc:h2:mem:togglz;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

togglz.console.enabled=true
togglz.console.path=/actuator/features
togglz.console.secured=false
togglz.console.feature-admin-authority=ROLE_1
togglz.console.use-management-port=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
