CREATE TABLE INVESTOR (
  IDT_INVESTOR varchar(100) not null,
  IND_PROFILE varchar(30) not null,
  DAT_CREATED timestamp not null default timezone('UTC', clock_timestamp()),
  DAT_UPDATED timestamp,
  CONSTRAINT INVESTOR_PK PRIMARY KEY (IDT_INVESTOR)
);

CREATE TABLE WALLET (
  IDT_WALLET varchar(100) not null,
  IDT_INVESTOR varchar(100) not null,
  IND_STATUS varchar(30) not null,
  DAT_READY timestamp,
  DAT_ABORTED timestamp,
  DAT_CREATED timestamp not null default timezone('UTC', clock_timestamp()),
  DAT_UPDATED timestamp,
  CONSTRAINT WALLET_PK PRIMARY KEY (IDT_WALLET)
);

CREATE INDEX WALLET_IDX1
  ON WALLET (IDT_INVESTOR, DAT_CREATED);

CREATE TABLE INVESTMENT (
  IDT_INVESTMENT varchar(100) not null,
  IDT_WALLET varchar(100) not null,
  IDT_INVESTOR varchar(100) not null,
  IDT_BASE_INVESTMENT varchar(100) not null,
  IND_PROFILE varchar(30) not null,
  FLG_CREATED boolean not null,
  DAT_CREATED timestamp not null default timezone('UTC', clock_timestamp()),
  DAT_UPDATED timestamp,
  CONSTRAINT INVESTMENT_PK PRIMARY KEY (IDT_INVESTMENT)
);

CREATE INDEX INVESTMENT_IDX1
  ON INVESTMENT (IDT_WALLET);

CREATE INDEX INVESTMENT_IDX2
  ON INVESTMENT (IDT_INVESTOR, IND_PROFILE);

CREATE TABLE FINANCIAL_EVENT_CANDIDATE (
  IDT_FINANCIAL_EVENT_CANDIDATE varchar(100) not null,
  IDT_INVESTMENT varchar(100) not null,
  IND_STATUS varchar(30) not null,
  FLG_PROCESSED boolean not null,
  NUM_ATTEMPTS integer not null,
  DAT_PROCESSED timestamp,
  DAT_CREATED timestamp not null default timezone('UTC', clock_timestamp()),
  DAT_UPDATED timestamp,
  CONSTRAINT FINANCIAL_EVENT_CANDIDATE_PK PRIMARY KEY (IDT_FINANCIAL_EVENT_CANDIDATE)
);

CREATE INDEX FINANCIAL_EVENT_CANDIDATE_IDX1
  ON FINANCIAL_EVENT_CANDIDATE (IDT_INVESTMENT);

CREATE INDEX FINANCIAL_EVENT_CANDIDATE_IDX2
  ON FINANCIAL_EVENT_CANDIDATE (IND_STATUS, FLG_PROCESSED);

ALTER TABLE WALLET
  ADD CONSTRAINT WALLET_FK1
  FOREIGN KEY (IDT_INVESTOR)
  REFERENCES INVESTOR (IDT_INVESTOR)
  ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE INVESTMENT
  ADD CONSTRAINT INVESTMENT_FK1
  FOREIGN KEY (IDT_WALLET)
  REFERENCES WALLET (IDT_WALLET)
  ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE INVESTMENT
  ADD CONSTRAINT INVESTMENT_FK2
  FOREIGN KEY (IDT_INVESTOR)
  REFERENCES INVESTOR (IDT_INVESTOR)
  ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE FINANCIAL_EVENT_CANDIDATE
  ADD CONSTRAINT FINANCIAL_EVENT_CANDIDATE_FK1
  FOREIGN KEY (IDT_INVESTMENT)
  REFERENCES INVESTMENT (IDT_INVESTMENT)
  ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
