CREATE TABLE INV.INVESTOR (
  IDT_INVESTOR VARCHAR(100) NOT NULL,
  IND_PROFILE VARCHAR(30) NOT NULL,
  DAT_CREATED TIMESTAMP NOT NULL DEFAULT TIMEZONE('UTC', CLOCK_TIMESTAMP()),
  DAT_UPDATED TIMESTAMP,
  CONSTRAINT INVESTOR_PK PRIMARY KEY (IDT_INVESTOR)
);

CREATE TABLE INV.WALLET (
  IDT_WALLET VARCHAR(100) NOT NULL,
  IDT_INVESTOR VARCHAR(100) NOT NULL,
  IND_STATUS VARCHAR(30) NOT NULL,
  DAT_READY TIMESTAMP,
  DAT_ABORTED TIMESTAMP,
  DAT_CREATED TIMESTAMP NOT NULL DEFAULT TIMEZONE('UTC', CLOCK_TIMESTAMP()),
  DAT_UPDATED TIMESTAMP,
  CONSTRAINT WALLET_PK PRIMARY KEY (IDT_WALLET)
);

CREATE INDEX WALLET_IDX1
  ON INV.WALLET (IDT_INVESTOR, DAT_CREATED);

CREATE TABLE INV.INVESTMENT (
  IDT_INVESTMENT VARCHAR(100) NOT NULL,
  IDT_WALLET VARCHAR(100) NOT NULL,
  IDT_INVESTOR VARCHAR(100) NOT NULL,
  IDT_BASE_INVESTMENT VARCHAR(100) NOT NULL,
  IND_PROFILE VARCHAR(30) NOT NULL,
  FLG_CREATED BOOLEAN NOT NULL,
  DAT_CREATED TIMESTAMP NOT NULL DEFAULT TIMEZONE('UTC', CLOCK_TIMESTAMP()),
  DAT_UPDATED TIMESTAMP,
  CONSTRAINT INVESTMENT_PK PRIMARY KEY (IDT_INVESTMENT)
);

CREATE INDEX INVESTMENT_IDX1
  ON INV.INVESTMENT (IDT_WALLET);

CREATE INDEX INVESTMENT_IDX2
  ON INV.INVESTMENT (IDT_INVESTOR, IND_PROFILE);

CREATE TABLE INV.FINANCIAL_EVENT_CANDIDATE (
  IDT_FINANCIAL_EVENT_CANDIDATE VARCHAR(100) NOT NULL,
  IDT_INVESTMENT VARCHAR(100) NOT NULL,
  IND_STATUS VARCHAR(30) NOT NULL,
  FLG_PROCESSED BOOLEAN NOT NULL,
  NUM_ATTEMPTS INTEGER NOT NULL,
  DAT_PROCESSED TIMESTAMP,
  DAT_CREATED TIMESTAMP NOT NULL DEFAULT TIMEZONE('UTC', CLOCK_TIMESTAMP()),
  DAT_UPDATED TIMESTAMP,
  CONSTRAINT FINANCIAL_EVENT_CANDIDATE_PK PRIMARY KEY (IDT_FINANCIAL_EVENT_CANDIDATE)
);

CREATE INDEX FINANCIAL_EVENT_CANDIDATE_IDX1
  ON INV.FINANCIAL_EVENT_CANDIDATE (IDT_INVESTMENT);

CREATE INDEX FINANCIAL_EVENT_CANDIDATE_IDX2
  ON INV.FINANCIAL_EVENT_CANDIDATE (IND_STATUS, FLG_PROCESSED);

ALTER TABLE INV.WALLET
  ADD CONSTRAINT WALLET_FK1
  FOREIGN KEY (IDT_INVESTOR)
  REFERENCES INV.INVESTOR (IDT_INVESTOR)
  ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE INV.INVESTMENT
  ADD CONSTRAINT INVESTMENT_FK1
  FOREIGN KEY (IDT_WALLET)
  REFERENCES INV.WALLET (IDT_WALLET)
  ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE INV.INVESTMENT
  ADD CONSTRAINT INVESTMENT_FK2
  FOREIGN KEY (IDT_INVESTOR)
  REFERENCES INV.INVESTOR (IDT_INVESTOR)
  ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE INV.FINANCIAL_EVENT_CANDIDATE
  ADD CONSTRAINT FINANCIAL_EVENT_CANDIDATE_FK1
  FOREIGN KEY (IDT_INVESTMENT)
  REFERENCES INV.INVESTMENT (IDT_INVESTMENT)
  ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
